# Generated by Django 4.0.5 on 2022-06-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statnam', models.CharField(max_length=100)),
                ('lang', models.CharField(max_length=100)),
                ('food', models.CharField(max_length=100)),
                ('fest', models.CharField(max_length=100)),
                ('art', models.CharField(max_length=500)),
                ('sport', models.CharField(max_length=100)),
                ('arch', models.CharField(max_length=100)),
                ('cloth', models.CharField(max_length=200)),
                ('tribe', models.CharField(max_length=500)),
            ],
        ),
    ]
