# Generated by Django 4.0.5 on 2022-06-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thetianzu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statnam', models.CharField(max_length=100)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
    ]
