# Generated by Django 4.0.5 on 2022-06-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thetianzu', '0002_loc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statesdata',
            name='arch',
            field=models.CharField(max_length=1000),
        ),
    ]
